#! /bin/sh

if [ "$1" != "-no_graphics" ]
then
  options=" +gui +ncaccess+r +tcl+testbench/arm_soc.tcl"
  shift
fi

HEXPROG=software/code.hex
PROGRAM=" +define+prog_file=${HEXPROG}"

if [ -f "$1" ]
then
  testbench=$1
else
  testbench=testbench/arm_soc_stim.sv
fi

ncverilog -sv $testbench -y behavioural +libext+.sv $options $PROGRAM

