# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/rasterizer.xdc

# Block Designs: bd/rasterizer_ee712/rasterizer_ee712.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712 || ORIG_REF_NAME==rasterizer_ee712} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_processing_system7_0_0/rasterizer_ee712_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_processing_system7_0_0 || ORIG_REF_NAME==rasterizer_ee712_processing_system7_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_proc_sys_reset_0_0/rasterizer_ee712_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_proc_sys_reset_0_0 || ORIG_REF_NAME==rasterizer_ee712_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_smartconnect_0_0/rasterizer_ee712_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_smartconnect_0_0 || ORIG_REF_NAME==rasterizer_ee712_smartconnect_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_axi_gpio_0_0/rasterizer_ee712_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_axi_gpio_0_0 || ORIG_REF_NAME==rasterizer_ee712_axi_gpio_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_clk_wiz_0_0/rasterizer_ee712_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_clk_wiz_0_0 || ORIG_REF_NAME==rasterizer_ee712_clk_wiz_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_v_tc_0_0/rasterizer_ee712_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_v_tc_0_0 || ORIG_REF_NAME==rasterizer_ee712_v_tc_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_xlconstant_0_0/rasterizer_ee712_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_xlconstant_0_0 || ORIG_REF_NAME==rasterizer_ee712_xlconstant_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_proc_sys_reset_1_0/rasterizer_ee712_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_proc_sys_reset_1_0 || ORIG_REF_NAME==rasterizer_ee712_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_v_axi4s_vid_out_0_0/rasterizer_ee712_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==rasterizer_ee712_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_xlconstant_1_0/rasterizer_ee712_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_xlconstant_1_0 || ORIG_REF_NAME==rasterizer_ee712_xlconstant_1_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_rgb2dvi_0_0/rasterizer_ee712_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_rgb2dvi_0_0 || ORIG_REF_NAME==rasterizer_ee712_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/rasterizer_ee712/ip/rasterizer_ee712_rasterizer20_1_0/rasterizer_ee712_rasterizer20_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rasterizer_ee712_rasterizer20_1_0 || ORIG_REF_NAME==rasterizer_ee712_rasterizer20_1_0} -quiet] -quiet

# XDC: c:/Users/root/Downloads/rasterizer_ee712_project/rasterizer_ee712_project.gen/sources_1/bd/rasterizer_ee712/rasterizer_ee712_ooc.xdc
