# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/root/Downloads/rasterizer_ee712_project/rasterizer_ee712_project.srcs/sources_1/bd/rasterizer_ee712/ip/rasterizer_ee712_v_axi4s_vid_out_0_0/rasterizer_ee712_v_axi4s_vid_out_0_0.xci
# IP: The module: 'rasterizer_ee712_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/root/Downloads/rasterizer_ee712_project/rasterizer_ee712_project.gen/sources_1/bd/rasterizer_ee712/ip/rasterizer_ee712_v_axi4s_vid_out_0_0/rasterizer_ee712_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rasterizer_ee712_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/root/Downloads/rasterizer_ee712_project/rasterizer_ee712_project.gen/sources_1/bd/rasterizer_ee712/ip/rasterizer_ee712_v_axi4s_vid_out_0_0/rasterizer_ee712_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rasterizer_ee712_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/root/Downloads/rasterizer_ee712_project/rasterizer_ee712_project.srcs/sources_1/bd/rasterizer_ee712/ip/rasterizer_ee712_v_axi4s_vid_out_0_0/rasterizer_ee712_v_axi4s_vid_out_0_0.xci
# IP: The module: 'rasterizer_ee712_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/root/Downloads/rasterizer_ee712_project/rasterizer_ee712_project.gen/sources_1/bd/rasterizer_ee712/ip/rasterizer_ee712_v_axi4s_vid_out_0_0/rasterizer_ee712_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rasterizer_ee712_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/root/Downloads/rasterizer_ee712_project/rasterizer_ee712_project.gen/sources_1/bd/rasterizer_ee712/ip/rasterizer_ee712_v_axi4s_vid_out_0_0/rasterizer_ee712_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rasterizer_ee712_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
