domain_path: C:\Users\root\Downloads\rasterizer_ee712_project\rast_esd_plat3\export\rast_esd_plat3\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
